name: flutter_init
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  go_router: ^16.2.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  retrofit_generator: ^10.0.2
  json_serializable: ^6.11.0

#flutter_gen:
#  output: lib/generated/
#
#  integrations:
#    flutter_svg: true
#    flare_flutter: true
#    rive: true
#    lottie: true
#
#  assets:
#    enabled: true
#    outputs:
#      package_parameter_enabled: true
#      class_name: ResAssets
#
#  fonts:
#    enabled: true



flutter:
  uses-material-design: true

  assets:
    - .env.dev

